name = "rylis"
version = "1.0.0"
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_httpc = ">= 2.2.0 and < 3.0.0"
gleam_json = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
wisp = ">= 0.14.0 and < 1.0.0"
mist = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
nakai = ">= 0.10.0 and < 1.0.0"
glenvy = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
glailglind = ">= 1.1.1 and < 2.0.0"


[tailwind]
version = "3.4.3"
args = [
    "--config=tailwind.config.js",
    "--input=./src/css/app.css",
    "--output=./priv/static/css/app.css"
]
